import type { Metadata } from 'next'

import '@/styles/globals.css'

import { Archivo } from 'next/font/google'
import type { FC, ReactNode } from 'react'

export const metadata: Metadata = {
  title: '1 Copa Consagrados',
  description: 'Generated by create next app',
}

const archivo = Archivo({
  subsets: ['latin'],
  variable: '--font-archivo',
})

type LayoutProps = {
  children: ReactNode
}

const RootLayout: FC<LayoutProps> = ({ children }) => {
  return (
    <html lang="pt-BR">
      <body className={`${archivo.variable} antialiased dark`}>{children}</body>
    </html>
  )
}

export default RootLayout
